config/routes.rb
Rails.application.routes.draw do
  resources :compras
  resources :autos

  root 'compras#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto.rb
class Auto < ApplicationRecord
end

app/models/compra.rb
class Compra < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  before_action :set_auto, only: [:show, :edit, :update, :destroy]

  # GET /autos
  # GET /autos.json
  def index
    @autos = Auto.all
  end

  # GET /autos/1
  # GET /autos/1.json
  def show
  end

  # GET /autos/new
  def new
    @auto = Auto.new
  end

  # GET /autos/1/edit
  def edit
  end

  # POST /autos
  # POST /autos.json
  def create
    @auto = Auto.new(auto_params)

    respond_to do |format|
      if @auto.save
        format.html { redirect_to @auto, notice: 'Auto was successfully created.' }
        format.json { render :show, status: :created, location: @auto }
      else
        format.html { render :new }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autos/1
  # PATCH/PUT /autos/1.json
  def update
    respond_to do |format|
      if @auto.update(auto_params)
        format.html { redirect_to @auto, notice: 'Auto was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto }
      else
        format.html { render :edit }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autos/1
  # DELETE /autos/1.json
  def destroy
    @auto.destroy
    respond_to do |format|
      format.html { redirect_to autos_url, notice: 'Auto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto
      @auto = Auto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_params
      params.require(:auto).permit(:marca, :modelo, :anio, :precio, :fechaAdq)
    end
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:Fecha_Compra, :Monto, :Cliente, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/views/autos/_form.html.erb
<%= form_for(auto) do |f| %>
  <% if auto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auto.errors.count, "error") %> prohibited this auto from being saved:</h2>

      <ul>
      <% auto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marca %>
    <%= f.text_field :marca %>
  </div>

  <div class="field">
    <%= f.label :modelo %>
    <%= f.text_field :modelo %>
  </div>

  <div class="field">
    <%= f.label :anio %>
    <%= f.text_field :anio %>
  </div>

  <div class="field">
    <%= f.label :precio %>
    <%= f.text_field :precio %>
  </div>

  <div class="field">
    <%= f.label :fechaAdq %>
    <%= f.date_select :fechaAdq %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/autos/edit.html.erb
<h1>Editing Auto</h1>

<%= render 'form', auto: @auto %>

<%= link_to 'Show', @auto %> |
<%= link_to 'Back', autos_path %>

app/views/autos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Autos</h1>

<table>
  <thead>
    <tr>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Anio</th>
      <th>Precio</th>
      <th>Fechaadq</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @autos.each do |auto| %>
      <tr>
        <td><%= auto.marca %></td>
        <td><%= auto.modelo %></td>
        <td><%= auto.anio %></td>
        <td><%= auto.precio %></td>
        <td><%= auto.fechaAdq %></td>
        <td><%= link_to 'Show', auto %></td>
        <td><%= link_to 'Edit', edit_auto_path(auto) %></td>
        <td><%= link_to 'Destroy', auto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auto', new_auto_path %>

app/views/autos/new.html.erb
<h1>New Auto</h1>

<%= render 'form', auto: @auto %>

<%= link_to 'Back', autos_path %>

app/views/autos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @auto.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @auto.modelo %>
</p>

<p>
  <strong>Anio:</strong>
  <%= @auto.anio %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @auto.precio %>
</p>

<p>
  <strong>Fechaadq:</strong>
  <%= @auto.fechaAdq %>
</p>

<%= link_to 'Edit', edit_auto_path(@auto) %> |
<%= link_to 'Back', autos_path %>

app/views/compras/_form.html.erb
<%= form_for(compra) do |f| %>
  <% if compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Fecha_Compra %>
    <%= f.date_select :Fecha_Compra %>
  </div>

  <div class="field">
    <%= f.label :Monto %>
    <%= f.text_field :Monto %>
  </div>

  <div class="field">
    <%= f.label :Cliente %>
    <%= f.text_field :Cliente %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Show', @compra %> |
<%= link_to 'Back', compras_path %>

app/views/compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Compras</h1>

<table>
  <thead>
    <tr>
      <th>Fecha compra</th>
      <th>Monto</th>
      <th>Cliente</th>
      <th>Text</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td><%= compra.Fecha_Compra %></td>
        <td><%= compra.Monto %></td>
        <td><%= compra.Cliente %></td>
        <td><%= compra.text %></td>
        <td><%= link_to 'Show', compra,
                                class:'button radius'%></td>
        <td><%= link_to 'Edit', edit_compra_path(compra),
                                class:'button radius success'%></td>
        <td><%= link_to 'Destroy', compra,
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class:'class button alert'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compra', new_compra_path%>

app/views/compras/new.html.erb
<h1>New Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Back', compras_path %>

app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha compra:</strong>
  <%= @compra.Fecha_Compra %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @compra.Monto %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @compra.Cliente %>
</p>

<p>
  <strong>Text:</strong>
  <%= @compra.text %>
</p>

<%= link_to 'Edit', edit_compra_path(@compra) %> |
<%= link_to 'Back', compras_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectScaffol</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>